# Site configuration

# Base URL
baseurl: ""

# Site live URL
url: https://spxrogers.com

# Localhost
#url: http://127.0.0.1:4000

harmony:
  name: Steven Rogers
  # Used in <meta name="description"> and feed.xml site description.
  meta_description: >
   Steven Rogers - software engineer, family man, and collector of unlikely hobbies. Based in NYC.

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-64521528-1

# Conversion / Build settings
markdown: kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CLAUDE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - justfile
  - .gitignore
  - .sass-cache

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: compressed
